In [1]:
import numpy as np
import pandas as pd
import math
import copy

from scipy.spatial import distance

In [2]:
data1 = pd.read_csv("/content/DATA COLLECTION for Line segment (Responses).csv")
data1.head()

Timestamp          Name  \
0  5/25/2023 14:23:12          Ab D   
1  5/25/2023 14:30:12         P Das   
2  5/25/2023 14:43:11  Abhijan Das    
3  5/25/2023 14:44:31           pra   
4  5/25/2023 15:05:42     Deb Kundu   

  Put longitute and latitute seperated by ',' of the one end for the first line segment. Example:  22.658942, 88.376635 \n(NA means you dont want to put the points. So request not to  select NA)  \
0                                                NaN                                                                                                                                                 
1                              22.652093, 88.377089                                                                                                                                                  
2                              22.652093, 88.377089                                                                                                                                                  
3                               22.658942, 88.376635                                                                                                                                                 
4                               22.643446, 88.377509                                                                                                                                                 

  Put longitute and latitute seperated by ',' of the one end  for the second line segment  .  Example:  22.658942, 88.376635 \n(NA means you dont want to put data. So request not to select NA  )  \
0                                                NaN                                                                                                                                                 
1                               22.652121, 88.377154                                                                                                                                                 
2                               22.652121, 88.377154                                                                                                                                                 
3                               22.698942, 88.386635                                                                                                                                                 
4                               22.643908, 88.376045                                                                                                                                                 

  Put longitute and latitute seperated by ',' of the one end  for the third line segment.   Example:  22.658942, 88.376635 \n(NA means you dont want to put data. So request not to select NA  )  \
0                                                NaN                                                                                                                                               
1                                22.652197,88.377162                                                                                                                                               
2                                22.652197,88.377162                                                                                                                                               
3                               29.658942, 88.376635                                                                                                                                               
4                               22.644322, 88.375740                                                                                                                                               

  Put the longitute and latitute of the other end seperated by ','  for the first line segment . Example:  22.658942, 88.376635 \n(NA means you dont want to put the points. So request not to  select NA)  \
0               

In [3]:
data2 = data1.dropna()
data2

Timestamp             Name  \
1   5/25/2023 14:30:12            P Das   
2   5/25/2023 14:43:11     Abhijan Das    
3   5/25/2023 14:44:31              pra   
4   5/25/2023 15:05:42        Deb Kundu   
6   5/25/2023 15:13:56  Dipu Mukherjee    
9    5/26/2023 0:01:33              D K   
11  5/28/2023 12:23:43       Anil Barik   
12  5/31/2023 11:26:08        Pavel Kar   
13  5/31/2023 11:29:22       Rajib Paul   
14  5/31/2023 11:31:30     Monojit Nath   
15   6/1/2023 18:29:21         Pradip D   
16   6/1/2023 18:56:01     Majhil singh   

   Put longitute and latitute seperated by ',' of the one end for the first line segment. Example:  22.658942, 88.376635 \n(NA means you dont want to put the points. So request not to  select NA)  \
1                               22.652093, 88.377089                                                                                                                                                  
2                               22.652093, 88.377089                                                                                                                                                  
3                                22.658942, 88.376635                                                                                                                                                 
4                                22.643446, 88.377509                                                                                                                                                 
6                                 22.852889,88.753983                                                                                                                                                 
9                                22.646879, 88.376164                                                                                                                                                 
11                               22.646133, 88.375575                                                                                                                                                 
12                               22.646720, 88.375284                                                                                                                                                 
13                               22.643822, 88.376494                                                                                                                                                 
14                               22.651499, 88.376825                                                                                                                                                 
15                               22.644588, 88.375077                                                                                                                                                 
16                               22.647155, 88.375697                                                                                                                                                 

   Put longitute and latitute seperated by ',' of the one end  for the second line segment  .  Example:  22.658942, 88.376635 \n(NA means you dont want to put data. So request not to select NA  )  \
1                                22.652121, 88.377154                                                                                                                                                 
2                                22.652121, 88.377154                                                                                                                                                 
3                                22.698942, 88.386635                                                                                                                                                 
4                                22.643908, 88.376045                

In [4]:
data3 = data2.drop(data2.columns[0],axis=1)
data3

Name  \
1             P Das   
2      Abhijan Das    
3               pra   
4         Deb Kundu   
6   Dipu Mukherjee    
9               D K   
11       Anil Barik   
12        Pavel Kar   
13       Rajib Paul   
14     Monojit Nath   
15         Pradip D   
16     Majhil singh   

   Put longitute and latitute seperated by ',' of the one end for the first line segment. Example:  22.658942, 88.376635 \n(NA means you dont want to put the points. So request not to  select NA)  \
1                               22.652093, 88.377089                                                                                                                                                  
2                               22.652093, 88.377089                                                                                                                                                  
3                                22.658942, 88.376635                                                                                                                                                 
4                                22.643446, 88.377509                                                                                                                                                 
6                                 22.852889,88.753983                                                                                                                                                 
9                                22.646879, 88.376164                                                                                                                                                 
11                               22.646133, 88.375575                                                                                                                                                 
12                               22.646720, 88.375284                                                                                                                                                 
13                               22.643822, 88.376494                                                                                                                                                 
14                               22.651499, 88.376825                                                                                                                                                 
15                               22.644588, 88.375077                                                                                                                                                 
16                               22.647155, 88.375697                                                                                                                                                 

   Put longitute and latitute seperated by ',' of the one end  for the second line segment  .  Example:  22.658942, 88.376635 \n(NA means you dont want to put data. So request not to select NA  )  \
1                                22.652121, 88.377154                                                                                                                                                 
2                                22.652121, 88.377154                                                                                                                                                 
3                                22.698942, 88.386635                                                                                                                                                 
4                                22.643908, 88.376045                                                                                                                                                 
6                                22.682938, 88.376666                                                                               

In [5]:
Dict = {'Annotator' : [i for i in range(len(data3))], 
        '1st_of_1st_line' : list(data3[data3.columns[1]]), 
        '2nd_of_1st_line' : list(data3[data3.columns[2]]), 
        '1st_of_2nd_line' : list(data3[data3.columns[3]]), 
        '2nd_of_2nd_line' : list(data3[data3.columns[4]]), 
        '1st_of_3rd_line' : list(data3[data3.columns[5]]), 
        '2nd_of_3rd_line' : list(data3[data3.columns[6]])
        }

data = pd.DataFrame(Dict)
data

Annotator        1st_of_1st_line       2nd_of_1st_line  \
0           0  22.652093, 88.377089   22.652121, 88.377154   
1           1  22.652093, 88.377089   22.652121, 88.377154   
2           2   22.658942, 88.376635  22.698942, 88.386635   
3           3   22.643446, 88.377509  22.643908, 88.376045   
4           4    22.852889,88.753983  22.682938, 88.376666   
5           5   22.646879, 88.376164  22.645326, 88.375832   
6           6   22.646133, 88.375575  22.651084, 88.376863   
7           7   22.646720, 88.375284  22.646594, 88.377372   
8           8   22.643822, 88.376494  22.646002, 88.376794   
9           9   22.651499, 88.376825  22.647549, 88.376692   
10         10   22.644588, 88.375077  22.651542, 88.376907   
11         11   22.647155, 88.375697  22.649385, 88.376514   

         1st_of_2nd_line       2nd_of_2nd_line       1st_of_3rd_line  \
0    22.652197,88.377162   22.652162,88.377197  22.647359, 88.376395   
1    22.652197,88.377162   22.652162,88.377197   22.643217,88.377217   
2   29.658942, 88.376635  22.698942, 88.386635  32.658942, 78.376635   
3   22.644322, 88.375740  22.644589, 88.376289  22.647359, 88.376395   
4    22.652197,88.377162   22.652162,88.377197   22.643217,88.377217   
5   22.648009, 88.377078  22.647656, 88.376316  22.645764, 88.375898   
6   22.647836, 88.375876  22.646787, 88.375404  22.650688, 88.376605   
7   22.649345, 88.377159  22.645164, 88.374914  22.647366, 88.377341   
8   22.648952, 88.375973  22.643934, 88.376749  22.646578, 88.376792   
9   22.646530, 88.375575  22.650707, 88.376427  22.647601, 88.375650   
10  22.643778, 88.375990  22.643406, 88.374711  22.649712, 88.377029   
11  22.646656, 88.376403  22.649385, 88.376514  22.646656, 88.376403   

         2nd_of_3rd_line  
0   22.648986, 88.376083  
1   22.643307, 88.377301  
2   32.698942, 78.386635  
3   22.648986, 88.376083  
4   22.643307, 88.377301  
5   22.648007, 88.376481  
6   22.647559, 88.376048  
7   22.649484, 88.376459  
8   22.648739, 88.376456  
9   22.645977, 88.376956  
10  22.643683, 88.376944  
11  22.648463, 88.377173

In [6]:
data.to_csv('Response.csv')

In [7]:
def swap(p, q):
    return q.copy(), p.copy()

In [8]:
def valid_length(R, max_len):
    distances = np.linalg.norm(R[:, 0] - R[:, 1], axis=1)
    mask = distances <= max_len

    List = R[mask]
    IndexList = np.where(mask)[0]

    return List, IndexList

In [9]:
def valid_distance(List, IndexList, i, j, min_dis):
    d1 = math.dist(List[i][0], List[j][0])
    if d1 < min_dis:
        List = np.delete(List, j, axis = 0)
        IndexList = np.delete(IndexList, j)
    else:
        d2 = math.dist(List[i][0], List[j][1])
        if d2 < min_dis:
            List = np.delete(List, j, axis = 0)
            IndexList = np.delete(IndexList, j)
        else:
            d3 = math.dist(List[i][1], List[j][0])
            if d3 < min_dis:
                List = np.delete(List, j, axis = 0)
                IndexList = np.delete(IndexList, j)
            else:
                d4 = math.dist(List[i][1], List[j][1])
                if d4 < min_dis:
                    List = np.delete(List, j, axis = 0)
                    IndexList = np.delete(IndexList, j)
                else:
                    j = j + 1
    return List, IndexList, j

In [10]:
def find_mean(R, A, Tot, freq):
    A[0] += freq * (R[0] - A[0]) / Tot
    A[1] += freq * (R[1] - A[1]) / Tot
    A = np.array([A[0], A[1]])
    return A

In [11]:
#R is the response of one annotator, A is the array of previously stored points
def find_multiple_lines(R, A, Tot, min_dis, max_len): 
    #Sorting line segment
    for i in range(len(R)):
        if R[i][0][0] > R[i][1][0]:
            R[i][0], R[i][1] = swap(R[i][0], R[i][1])
        elif R[i][0][0] == R[i][1][0]:
            if R[i][0][1] > R[i][1][1]:
                R[i][0], R[i][1] = swap(R[i][0], R[i][1])
            
    for i in range(len(R)):
        for j in range(i + 1, len(R)):
            if R[i][0][0] > R[j][0][0]:
                R[i], R[j] = swap(R[i], R[j])
            elif R[i][1][0] == R[i][1][0]:
                if R[i][0][1] > R[j][0][1]:
                    R[i], R[j] = swap(R[i], R[j])


    #Length check for valid entry
    List, IndexList = valid_length(R, max_len)
    # R = None

    #Distance check for valid entry
    i = 0
    while i < (len(List)):
        j = i + 1
        while j < len(List):
            List, IndexList, j = valid_distance(List, IndexList, i, j, min_dis)
        i = i + 1

    #Find mean
    freq = len(List)
    for i, index in enumerate(IndexList):
        Tot[index] += freq    #Put 'freq' times importance of the response

    # List = freq * List    #Put 'freq' times importance of the response
    for i, index in enumerate(IndexList):
        A[index] = find_mean(List[i], A[index], Tot[index], freq)

    return A, Tot


In [12]:
def make_response(s):
    Row_list = []
    for i in range(3):
        a = list(map(float, s[2*i+1].split(',')))
        b = list(map(float, s[2*i+2].split(',')))
        Row_list.append([a, b])
    return Row_list    

In [13]:
A = np.array([0.]*(3*4)).reshape(-1,2,2)
Tot = np.array([0]*3)
min_dis = 0.00076
max_len = 0.004


In [14]:
First_of_1st_line = [] 
Second_of_1st_line = []
First_of_2nd_line = [] 
Second_of_2nd_line = []
First_of_3rd_line = [] 
Second_of_3rd_line = []


In [15]:
for i in range(len(data)):
    s = data.iloc[i]
    Response = np.array(make_response(s))
    A, Tot = find_multiple_lines(Response, A, Tot, min_dis, max_len)
    First_of_1st_line.append(A[0][0])
    Second_of_1st_line.append(A[0][1])
    First_of_2nd_line.append(A[1][0])
    Second_of_2nd_line.append(A[1][1])
    First_of_3rd_line.append(A[2][0])
    Second_of_3rd_line.append(A[2][1])
    print(Tot)
    print(A)     

[2 2 0]
[[[22.647359 88.376395]
  [22.648986 88.376083]]

 [[22.652093 88.377089]
  [22.652121 88.377154]]

 [[ 0.        0.      ]
  [ 0.        0.      ]]]
[4 4 0]
[[[22.645288  88.376806 ]
  [22.6461465 88.376692 ]]

 [[22.652093  88.377089 ]
  [22.652121  88.377154 ]]

 [[ 0.         0.       ]
  [ 0.         0.       ]]]
[4 4 0]
[[[22.645288  88.376806 ]
  [22.6461465 88.376692 ]]

 [[22.652093  88.377089 ]
  [22.652121  88.377154 ]]

 [[ 0.         0.       ]
  [ 0.         0.       ]]]
[6 6 0]
[[[22.644966   88.37645067]
  [22.64562733 88.37655767]]

 [[22.650515   88.37685767]
  [22.651076   88.376797  ]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]]
[8 8 0]
[[[22.64452875 88.37664225]
  [22.64504725 88.3767435 ]]

 [[22.65092675 88.3769425 ]
  [22.65135625 88.37688825]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]]
[10  8  2]
[[[22.6446882  88.3764802 ]
  [22.6454136  88.3766276 ]]

 [[22.65092675 88.3769425 ]
  [22.65135625 88.37688825]]

 [[22.64765

In [16]:
Dict1 = {'After Response of Annotator' : [i for i in range(len(data3))], 
        '1st_of_1st_line' : First_of_1st_line,
        '2nd_of_1st_line' : Second_of_1st_line, 
        '1st_of_2nd_line' : First_of_2nd_line, 
        '2nd_of_2nd_line' : Second_of_2nd_line, 
        '1st_of_3rd_line' : First_of_3rd_line, 
        '2nd_of_3rd_line' : Second_of_3rd_line
        }

data = pd.DataFrame(Dict1)
data.to_csv("Result.csv")